ORG 0H

LCD_DATA   EQU P0
LCD_CTRL   EQU P2
SELECTOR   EQU P1
BUTTON     EQU P3.0
LED        EQU P2.0

RS         EQU 0
EN         EQU 1

DELAY_BASE EQU 50000
TEMP_DELAY EQU 30H
EMERGENCY  EQU 31H

START:
    MOV TMOD, #01H
    CLR LED
    CLR EMERGENCY

MAIN_LOOP:
    JB BUTTON, EMERGENCY_MODE

    MOV A, SELECTOR
    MOV TEMP_DELAY, A

    ACALL DISPLAY_ROJO
    ACALL DELAY

    ACALL DISPLAY_AMARILLO
    ACALL DELAY

    ACALL DISPLAY_VERDE
    ACALL DELAY

    SJMP MAIN_LOOP

EMERGENCY_MODE:
    SETB LED
    ACALL DISPLAY_ALTO

WAIT_RELEASE:
    JNB BUTTON, WAIT_RELEASE
    CLR LED
    CLR EMERGENCY
    SJMP MAIN_LOOP

DISPLAY_ROJO:
    MOV DPTR, #MSG_ROJO
    ACALL DISPLAY_MESSAGE
    RET

DISPLAY_AMARILLO:
    MOV DPTR, #MSG_AMARILLO
    ACALL DISPLAY_MESSAGE
    RET

DISPLAY_VERDE:
    MOV DPTR, #MSG_VERDE
    ACALL DISPLAY_MESSAGE
    RET

DISPLAY_ALTO:
    MOV DPTR, #MSG_ALTO
    ACALL DISPLAY_MESSAGE
    RET

DISPLAY_MESSAGE:
    MOV R0, #0
SEND_CHAR:
    MOV A, @DPTR
    INC DPTR
    ORL A, A
    JZ SEND_DONE
    ACALL SEND_CHAR_TO_LCD
    SJMP SEND_CHAR

SEND_DONE:
    RET

SEND_CHAR_TO_LCD:
    MOV LCD_DATA, A
    SETB LCD_CTRL.RS
    SETB LCD_CTRL.EN
    CLR LCD_CTRL.EN
    RET

DELAY:
    MOV R0, TEMP_DELAY
DELAY_LOOP:
    MOV R1, #DELAY_BASE
INNER_DELAY:
    DJNZ R1, INNER_DELAY
    DJNZ R0, DELAY_LOOP
    RET

MSG_ROJO     DB 'ROJO', 0
MSG_AMARILLO DB 'AMARILLO', 0
MSG_VERDE    DB 'VERDE', 0
MSG_ALTO     DB 'ALTO', 0

END
